### ISSUE TITLE
unraid issue

### ISSUE THREAD

**Issue by reddai75** [patrickstigler/youtube-transcript-to-article#3]
hello! I have installed it on unraid, set the openaI API key, when I try to start the project it stops immediately... is there anything I am doing wrong ?

**Comment by patrickstigler** [comment]
Check if you used the dev build. 
So in case your used image is "patrickstigler/youtube-transcript-to-article:dev", change it to "patrickstigler/youtube-transcript-to-article".

**Comment by reddai75** [comment]
I am sorry I am not sure I understand.
I have installed the APP from the unraid menu option to install apps, so
everything is done automatically.
How am I supposed to proceed ?

**Comment by patrickstigler** [comment]
Depends on the time you installed the app.
I released a wrong config one, which was online for about a hour. So if you installed it druing that time, you used the dev image:

![image](https://github.com/user-attachments/assets/ea3cf7e6-7fc8-411d-8ad1-acaa789ffe90)

So check the first entry if it ends with ":dev", if so - remove the ":dev" part.

**Comment by patrickstigler** [comment]
Try to force update the container. I just updated the image.

**Comment by reddai75** [comment]
that is great thank you and sorry for the delay I tested it now and it works flawlessy
